/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.ManagementProcess;
import Model.Account;
import Model.BillInfo;
import Model.DBConnection;
import Model.Employee;
import java.awt.Image;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author kieum
 */
public class frmForEmoloyee extends javax.swing.JFrame {
    Employee defaultEmployee;
    ManagementProcess manager;
    boolean showOptionAccount=false;

    /**
     * Creates new form frmForEmoloyee
     */
    public frmForEmoloyee() {
        initComponents();
        setIMG();
        
        
    }
    public frmForEmoloyee(boolean isAdmin,Employee em){
        initComponents();
        setIMG();
        initConnection();
        defaultEmployee=em;
        btImport.setVisible(isAdmin);
        btImport.setEnabled(isAdmin);
        btEmployee.setVisible(isAdmin);
        btEmployee.setEnabled(isAdmin);
        jLabel2.setVisible(isAdmin);
        jLabel3.setVisible(isAdmin);
        if (isAdmin) {
            lbTitle.setText("Admin Management");
        }else
            lbTitle.setText("Seller Management");
        accountName.setText(em.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionAcoount = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        changePassDialog = new javax.swing.JDialog();
        txtPass2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtPass1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        editInfoDialog = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        txtEditID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEditName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEditYOB = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtEditAddr = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtEditSDT = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtEditEmail = new javax.swing.JTextField();
        btEdit = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        lbTitle = new javax.swing.JLabel();
        btCustomer = new javax.swing.JButton();
        btProduct = new javax.swing.JButton();
        btCategories = new javax.swing.JButton();
        btBill = new javax.swing.JButton();
        btImport = new javax.swing.JButton();
        btEmployee = new javax.swing.JButton();
        btOrder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbAccount = new javax.swing.JLabel();
        accountName = new javax.swing.JLabel();

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setText("Edit Infomation");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        optionAcoount.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem2.setText("Change Password?");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        optionAcoount.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem3.setText("Log out!");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        optionAcoount.add(jMenuItem3);

        changePassDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        changePassDialog.setTitle("Change password");
        changePassDialog.setMinimumSize(new java.awt.Dimension(400, 220));
        changePassDialog.setResizable(false);

        txtPass2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("New Password:");

        txtPass1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Retype:");

        javax.swing.GroupLayout changePassDialogLayout = new javax.swing.GroupLayout(changePassDialog.getContentPane());
        changePassDialog.getContentPane().setLayout(changePassDialogLayout);
        changePassDialogLayout.setHorizontalGroup(
            changePassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePassDialogLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(changePassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changePassDialogLayout.createSequentialGroup()
                        .addGroup(changePassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(changePassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPass1)
                            .addComponent(txtPass2))
                        .addGap(37, 37, 37))
                    .addGroup(changePassDialogLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(52, 52, 52))))
        );
        changePassDialogLayout.setVerticalGroup(
            changePassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePassDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(changePassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(changePassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(changePassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(34, 34, 34))
        );

        editInfoDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        editInfoDialog.setTitle("Edit Infomation");
        editInfoDialog.setMinimumSize(new java.awt.Dimension(389, 420));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Your ID:");

        txtEditID.setEditable(false);
        txtEditID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Your Name:");

        txtEditName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Year of Birth:");

        txtEditYOB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Address:");

        txtEditAddr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Phone:");

        txtEditSDT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Email:");

        txtEditEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btEdit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btEdit.setText("Edit");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editInfoDialogLayout = new javax.swing.GroupLayout(editInfoDialog.getContentPane());
        editInfoDialog.getContentPane().setLayout(editInfoDialogLayout);
        editInfoDialogLayout.setHorizontalGroup(
            editInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editInfoDialogLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(editInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14))
                .addGroup(editInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editInfoDialogLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtEditName, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editInfoDialogLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(editInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEditID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                .addComponent(txtEditYOB, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtEditAddr, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtEditSDT, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(txtEditEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editInfoDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(editInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editInfoDialogLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btCancel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editInfoDialogLayout.createSequentialGroup()
                        .addComponent(btEdit)
                        .addGap(187, 187, 187)))
                .addGap(68, 68, 68))
        );
        editInfoDialogLayout.setVerticalGroup(
            editInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editInfoDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEditID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(editInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEditName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(editInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEditYOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(editInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEditAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(editInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEditSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(editInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(editInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEdit)
                    .addComponent(btCancel))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 102, 102));
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("For Emploloyee");
        lbTitle.setFocusable(false);
        lbTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbTitle.setVerifyInputWhenFocusTarget(false);

        btCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCustomerActionPerformed(evt);
            }
        });

        btProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProductActionPerformed(evt);
            }
        });

        btCategories.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCategoriesActionPerformed(evt);
            }
        });

        btBill.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBillActionPerformed(evt);
            }
        });

        btImport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImportActionPerformed(evt);
            }
        });

        btEmployee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmployeeActionPerformed(evt);
            }
        });

        btOrder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrderActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Categories Manager");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Import Manager");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Employee Manager");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Order Manager");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Product Manager");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Customer Manager");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Bill Manager");

        lbAccount.setPreferredSize(new java.awt.Dimension(40, 40));
        lbAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAccountMouseClicked(evt);
            }
        });

        accountName.setText("Account");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(btCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(btImport, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(btBill, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
            .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accountName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(accountName)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btBill, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btImport, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCategoriesActionPerformed
        // TODO add your handling code here:
        new frmCategoriesmgr().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btCategoriesActionPerformed

    private void btProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProductActionPerformed
        // TODO add your handling code here:
        new frmProductMgr().setVisible(true);
    }//GEN-LAST:event_btProductActionPerformed

    private void btCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCustomerActionPerformed
        // TODO add your handling code here:
        new frmCustomerMgr().setVisible(true);
    }//GEN-LAST:event_btCustomerActionPerformed

    private void btBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBillActionPerformed
        // TODO add your handling code here:
        new frmBillMgr(defaultEmployee).setVisible(true);
    }//GEN-LAST:event_btBillActionPerformed

    private void btOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrderActionPerformed
        // TODO add your handling code here:
        new frmOrderMgr(defaultEmployee).setVisible(true);
    }//GEN-LAST:event_btOrderActionPerformed

    private void btImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImportActionPerformed
        // TODO add your handling code here:
        new frmImportProduct(defaultEmployee).setVisible(true);
    }//GEN-LAST:event_btImportActionPerformed

    private void btEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmployeeActionPerformed
        // TODO add your handling code here:
        new frmEmployeeMgr().setVisible(true);
    }//GEN-LAST:event_btEmployeeActionPerformed

    private void lbAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAccountMouseClicked
        // TODO add your handling code here:
        showOptionAccount=!showOptionAccount;
        optionAcoount.setVisible(showOptionAccount);
        optionAcoount.setLocation(lbAccount.getX()-60, lbAccount.getY()+80);
    }//GEN-LAST:event_lbAccountMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String passc=txtPass1.getText();
        if (!txtPass1.getText().equals(txtPass2.getText())) {
            JOptionPane.showMessageDialog(this, "Retype the same password!","error",JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                String pass=manager.getPass(defaultEmployee.getUsername());
                if (pass.equals(passc)) {
                    JOptionPane.showMessageDialog(this, "Please type other password!","error",JOptionPane.ERROR_MESSAGE);
                }else{
                    String type=manager.getAccountType(defaultEmployee.getUsername());
                    if (manager.updateAccount(defaultEmployee.getUsername(),new Account(defaultEmployee.getUsername(), passc,type))) {
                        if (JOptionPane.showConfirmDialog(changePassDialog,"Password Changed! Do you want Login agian?","Login again",JOptionPane.OK_CANCEL_OPTION)==0) {
                            new frmLogin(new Account(defaultEmployee.getUsername(), passc, type)).setVisible(true);
                            changePassDialog.dispose();
                            this.dispose();
                        }else
                        changePassDialog.dispose();

                    }

                }
            } catch (SQLException ex) {
                Logger.getLogger(frmForCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        changePassDialog.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        // TODO add your handling code here:
        Employee employee=new Employee(defaultEmployee.getId(),txtEditName.getText(), Integer.parseInt(txtEditYOB.getText()), txtEditAddr.getText(), txtEditSDT.getText(), txtEditEmail.getText(), defaultEmployee.getUsername());
        if (manager.updateEmployee(defaultEmployee.getId(), employee)) {
            JOptionPane.showMessageDialog(this, "Update Infomation Completed!");
            defaultEmployee=employee;
            editInfoDialog.dispose();
        }else
        JOptionPane.showMessageDialog(this, "Update Error!","Error",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btEditActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // TODO add your handling code here:
        editInfoDialog.dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        editInfoDialog.setVisible(true);
        editInfoDialog.setLocation(this.getX()+150, this.getY()+150);
        txtEditID.setText(String.valueOf(defaultEmployee.getId()));
        txtEditName.setText(defaultEmployee.getName());
        txtEditYOB.setText(String.valueOf(defaultEmployee.getYearOB()));
        txtEditAddr.setText(defaultEmployee.getAddress());
        txtEditSDT.setText(defaultEmployee.getPhone());
        txtEditEmail.setText(defaultEmployee.getEmail());
        optionAcoount.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        changePassDialog.setVisible(true);
        changePassDialog.setLocation(this.getX()+150, this.getY()+150);
        optionAcoount.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new frmLogin().setVisible(true);
        optionAcoount.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmForEmoloyee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmForEmoloyee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmForEmoloyee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmForEmoloyee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmForEmoloyee().setVisible(true);
            }
        });
    }
    private  void setIMG(){
        try {
            Image cate=ImageIO.read(getClass().getResourceAsStream("/Icon/cate.png")).getScaledInstance(btCategories.getWidth()-10, btCategories.getHeight()-10, Image.SCALE_SMOOTH); 
            Image em=ImageIO.read(getClass().getResourceAsStream("/Icon/Employee.png")).getScaledInstance(btCategories.getWidth()-10, btCategories.getHeight()-10, Image.SCALE_SMOOTH);
            Image bill=ImageIO.read(getClass().getResourceAsStream("/Icon/bill.png")).getScaledInstance(btCategories.getWidth()-10, btCategories.getHeight()-10, Image.SCALE_SMOOTH);
            Image cus=ImageIO.read(getClass().getResourceAsStream("/Icon/customer.jpg")).getScaledInstance(btCategories.getWidth()-10, btCategories.getHeight()-10, Image.SCALE_SMOOTH);
            Image importpro=ImageIO.read(getClass().getResourceAsStream("/Icon/import.png")).getScaledInstance(btCategories.getWidth()-10, btCategories.getHeight()-10, Image.SCALE_SMOOTH);
            Image pro=ImageIO.read(getClass().getResourceAsStream("/Icon/product.png")).getScaledInstance(btCategories.getWidth()-10, btCategories.getHeight()-10, Image.SCALE_SMOOTH);
            Image order=ImageIO.read(getClass().getResourceAsStream("/Icon/order.png")).getScaledInstance(btCategories.getWidth()-10, btCategories.getHeight()-10, Image.SCALE_SMOOTH);
            Image ac=ImageIO.read(getClass().getResourceAsStream("/Icon/account.png")).getScaledInstance(lbAccount.getWidth()-2, lbAccount.getHeight()-2, Image.SCALE_SMOOTH);
            btCategories.setIcon(new ImageIcon(cate));
            btProduct.setIcon(new ImageIcon(pro));
            btCustomer.setIcon(new ImageIcon(cus));
            btImport.setIcon(new ImageIcon(importpro));
            btEmployee.setIcon(new ImageIcon(em));
            btBill.setIcon(new ImageIcon(bill));
            btOrder.setIcon(new ImageIcon(order));
            lbAccount.setIcon(new ImageIcon(ac));
        } catch (IOException ex) {
            Logger.getLogger(frmForEmoloyee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void initConnection(){
        Connection con=new DBConnection().getConnection();
        manager=new ManagementProcess(con);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountName;
    private javax.swing.JButton btBill;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btCategories;
    private javax.swing.JButton btCustomer;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btEmployee;
    private javax.swing.JButton btImport;
    private javax.swing.JButton btOrder;
    private javax.swing.JButton btProduct;
    private javax.swing.JDialog changePassDialog;
    private javax.swing.JDialog editInfoDialog;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lbAccount;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPopupMenu optionAcoount;
    private javax.swing.JTextField txtEditAddr;
    private javax.swing.JTextField txtEditEmail;
    private javax.swing.JTextField txtEditID;
    private javax.swing.JTextField txtEditName;
    private javax.swing.JTextField txtEditSDT;
    private javax.swing.JTextField txtEditYOB;
    private javax.swing.JTextField txtPass1;
    private javax.swing.JTextField txtPass2;
    // End of variables declaration//GEN-END:variables
}
